# deploy_cronjob.yml
---
- name: Create Cron Job to Check Server Uptime
  hosts: slave
  become: true
  become_user: altschool

  tasks:
    - name: Create Cron Job to Check Server Uptime
      cron:
        name: 'Check_Server_Uptime'
        job: 'uptime >> /home/altschool/logs/uptime.log'
        special_time: daily
        state: present
      delegate_to: master
